<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <Nullable>enable</Nullable>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile
      Include="..\HtmlAgilityPack.Mod\**\*.cs"
      Link="HtmlAgilityPack\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
